/*
 * 부서별 평균, 최대, 최소 급여를 집계한 DEPT_SALARY_STATIS 테이블을 만들어 
 * 데이터를 추가하시오.
*/

DROP TABLE DEPT_SALARY_STATICS;
DROP TABLE JOB_SALARY_STATICS;

CREATE TABLE DEPT_SALARY_STATIS(
	    DEPT_AVG NUMBER
	  , DEPT_MAX NUMBER
	  , DEPT_MIN NUMBER
);

INSERT INTO DEPT_SALARY_STATIS (
		SELECT FLOOR(AVG(SALARY)) AS DEPT_AVG
			 , MAX(SALARY)		  AS DEPT_MAX
	 		 , MIN(SALARY)		  AS DEPT_MIN
		FROM EMPLOYEES
		WHERE DEPARTMENT_ID IS NOT NULL 
		GROUP BY DEPARTMENT_ID
);

SELECT * FROM DEPT_SALARY_STATIS;
/*
 * 직급별 평균, 최대, 최소 급여를 집계한 JOB_SALARY_SATIS 테이블을 만들어 
 * 데이터를 추가하시오. 
 */
CREATE TABLE JOB_SALARY_STATIS (
		JOB_ID VARCHAR2(10 CHAR)
	 ,	JOB_AVG NUMBER
	 ,  JOB_MAX NUMBER
	 ,  JOB_MIN NUMBER
);

INSERT INTO JOB_SALARY_STATIS(
			SELECT JOB_ID 
				  , FLOOR(AVG(SALARY))	AS JOB_AVG
	 			  , MAX(SALARY)			AS JOB_MAX
				  , MIN(SALARY) 		AS JOB_MIN
			FROM EMPLOYEES
			GROUP BY JOB_ID
);

SELECT * FROM JOB_SALARY_STATIS;
 /*
  * 직급 ID에 'MGR' 이 접두사로 붙은 JOB_SALARY_STATIS에 평균, 최대, 최소 급여를 +500 하세요.
*/
UPDATE JOB_SALARY_STATIS 
SET JOB_AVG = JOB_AVG + 500, JOB_MAX = JOB_MAX + 500, JOB_MIN = JOB_MIN + 500
WHERE JOB_ID LIKE '%MGR';

/*
 * 년도별 입사 인원을 파악하기 위한 HIRE_FOR_YEAR 테이블을 만들어 데이터를 추가하시오. 
 * (인원 파익이 주 목적이기 때문에 년도와 인원수만 저장할 수 있으면 됨)
 */
CREATE TABLE HIRE_FOR_YEAR (
		HIREYEAR NUMBER
	 ,  HIRECOUNT NUMBER
);

INSERT INTO HIRE_FOR_YEAR(
		SELECT EXTRACT(YEAR FROM HIRE_DATE) AS HIREYEAR
			 , COUNT(*)						AS HIRECOUNT
		FROM EMPLOYEES
		GROUP BY EXTRACT(YEAR FROM HIRE_DATE)
);

SELECT * FROM HIRE_FOR_YEAR;

DROP TABLE DEPT_SALARY_STATICS;
/*
 * 부서별 / 직급별 평균, 최대, 최소 급여를 저장한 테이블에 COMMISSION_PCT 까지 반영한 
 * 데이터가 저장될 수 있도록 기존 정보를 수정하시오. 
 */									 
-- DEPT_SALARY_SATICS
UPDATE DEPT_SALARY_STATIS 
SET		 (DEPT_AVG , DEPT_MAX, DEPT_MIN ) = ( SELECT FLOOR(AVG(SALARY * (1 + COMMISSION_PCT)))
																			   , MAX (SALARY * (1 + COMMISSION_PCT))			 
	 																		   , MIN(SALARY * (1 + COMMISSION_PCT))				
																	FROM EMPLOYEES
																	WHERE DEPARTMENT_ID IS NOT NULL
																	GROUP BY DEPARTMENT_ID);

-- JOB_SALARY_SATICS
SELECT 		 JOB_ID
					, FLOOR(AVG(SALARY * (1 + NVL(COMMISSION_PCT), 1)) AS DEPT_AVG
					 , MAX(SALARY * (1 + NVL(COMMISSION_PCT), 1))		  AS DEPT_MAX
	 				 , MIN(SALARY * (1 + NVL(COMMISSION_PCT), 1))		  AS DEPT_MIN
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL 
GROUP BY DEPARTMENT_ID;


