/*
 * DEPARTMENTS 테이블과 LOCATIONS 테이블을 사용하여 각 부서가 어느 지역에 
 * 위치하는지 알아내시오.
*/
SELECT D.DEPARTMENT_ID 
		   , D.DEPARTMENT_NAME 
		   , L.LOCATION_ID 
		  , L.STREET_ADDRESS 
		  , L.POSTAL_CODE 
		  ,L.CITY 
		  ,L.STATE_PROVINCE 
FROM DEPARTMENTS D
JOIN LOCATIONS L 
ON D.LOCATION_ID = L.LOCATION_ID
ORDER BY 1;

/*
 * 지역별로 몇 개의 부서가 배치되었는지 알아보세요.  
 */

SELECT COUNT(*) 부서수
		 , L.LOCATION_ID 
		  , L.STREET_ADDRESS 
		  , L.POSTAL_CODE 
		  ,L.CITY 
		  ,L.STATE_PROVINCE 
 FROM DEPARTMENTS D
 JOIN LOCATIONS L 
 ON D.LOCATION_ID = L.LOCATION_ID 
 GROUP BY L.LOCATION_ID 
 				, L.STREET_ADDRESS 
 				, L.POSTAL_CODE 
 				, L.CITY 
 				, L.STATE_PROVINCE;

/*
 * 지역 별 사원 수가 얼마나 되는지 알아보세요. 
*/
SELECT D.LOCATION_ID 지역번호 
			, COUNT(*) 사원수
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
GROUP BY D.LOCATION_ID;

